const mongoose = require("mongoose");


const marks = new mongoose.Schema({
    username: { type: String, required:true },
    mse1: { 
        DM:{
            _1a:{ type:Number,required:false},
            _1b:{ type:Number,required:false},
            _1c:{ type:Number,required:false},
            _2a:{ type:Number,required:false},
            _2b:{ type:Number,required:false},
            _2c:{ type:Number,required:false},
            _3a:{ type:Number,required:false},
            _3b:{ type:Number,required:false},
            _3c:{ type:Number,required:false},
        },
        SE:{
            _1a:{ type:Number,required:false},
            _1b:{ type:Number,required:false},
            _1c:{ type:Number,required:false},
            _2a:{ type:Number,required:false},
            _2b:{ type:Number,required:false},
            _2c:{ type:Number,required:false},
            _3a:{ type:Number,required:false},
            _3b:{ type:Number,required:false},
            _3c:{ type:Number,required:false},
        },
        CNS:{
            _1a:{ type:Number,required:false},
            _1b:{ type:Number,required:false},
            _1c:{ type:Number,required:false},
            _2a:{ type:Number,required:false},
            _2b:{ type:Number,required:false},
            _2c:{ type:Number,required:false},
            _3a:{ type:Number,required:false},
            _3b:{ type:Number,required:false},
            _3c:{ type:Number,required:false},
        },
        CE:{
            _1a:{ type:Number,required:false},
            _1b:{ type:Number,required:false},
            _1c:{ type:Number,required:false},
            _2a:{ type:Number,required:false},
            _2b:{ type:Number,required:false},
            _2c:{ type:Number,required:false},
            _3a:{ type:Number,required:false},
            _3b:{ type:Number,required:false},
            _3c:{ type:Number,required:false},
        },
    },
    mse2:{
        DM:{
            _1a:{ type:Number,required:false},
            _1b:{ type:Number,required:false},
            _1c:{ type:Number,required:false},
            _2a:{ type:Number,required:false},
            _2b:{ type:Number,required:false},
            _2c:{ type:Number,required:false},
            _3a:{ type:Number,required:false},
            _3b:{ type:Number,required:false},
            _3c:{ type:Number,required:false},
        },
        SE:{
            _1a:{ type:Number,required:false},
            _1b:{ type:Number,required:false},
            _1c:{ type:Number,required:false},
            _2a:{ type:Number,required:false},
            _2b:{ type:Number,required:false},
            _2c:{ type:Number,required:false},
            _3a:{ type:Number,required:false},
            _3b:{ type:Number,required:false},
            _3c:{ type:Number,required:false},
        },
        CNS:{
            _1a:{ type:Number,required:false},
            _1b:{ type:Number,required:false},
            _1c:{ type:Number,required:false},
            _2a:{ type:Number,required:false},
            _2b:{ type:Number,required:false},
            _2c:{ type:Number,required:false},
            _3a:{ type:Number,required:false},
            _3b:{ type:Number,required:false},
            _3c:{ type:Number,required:false},
        },
        CE:{
            _1a:{ type:Number,required:false},
            _1b:{ type:Number,required:false},
            _1c:{ type:Number,required:false},
            _2a:{ type:Number,required:false},
            _2b:{ type:Number,required:false},
            _2c:{ type:Number,required:false},
            _3a:{ type:Number,required:false},
            _3b:{ type:Number,required:false},
            _3c:{ type:Number,required:false},
        },
    },
    mse3:{
        DM:{
            _1a:{ type:Number,required:false},
            _1b:{ type:Number,required:false},
            _1c:{ type:Number,required:false},
            _2a:{ type:Number,required:false},
            _2b:{ type:Number,required:false},
            _2c:{ type:Number,required:false},
            _3a:{ type:Number,required:false},
            _3b:{ type:Number,required:false},
            _3c:{ type:Number,required:false},
        },
        SE:{
            _1a:{ type:Number,required:false},
            _1b:{ type:Number,required:false},
            _1c:{ type:Number,required:false},
            _2a:{ type:Number,required:false},
            _2b:{ type:Number,required:false},
            _2c:{ type:Number,required:false},
            _3a:{ type:Number,required:false},
            _3b:{ type:Number,required:false},
            _3c:{ type:Number,required:false},
        },
        CNS:{
            _1a:{ type:Number,required:false},
            _1b:{ type:Number,required:false},
            _1c:{ type:Number,required:false},
            _2a:{ type:Number,required:false},
            _2b:{ type:Number,required:false},
            _2c:{ type:Number,required:false},
            _3a:{ type:Number,required:false},
            _3b:{ type:Number,required:false},
            _3c:{ type:Number,required:false},
        },
        CE:{
            _1a:{ type:Number,required:false},
            _1b:{ type:Number,required:false},
            _1c:{ type:Number,required:false},
            _2a:{ type:Number,required:false},
            _2b:{ type:Number,required:false},
            _2c:{ type:Number,required:false},
            _3a:{ type:Number,required:false},
            _3b:{ type:Number,required:false},
            _3c:{ type:Number,required:false},
        },
    },
}, { collection: "marks" });

const model = mongoose.model("Marks", marks)
module.exports = model;